version: "3.8"

services:
  api:
    image: tm4soul.ch/tm4soulch-api:latest
    ports:
      - "8911:8911"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}

  web:
    image: tm4soul.ch/tm4soulch-web:latest
    ports:
      - "8910:8910"
    depends_on:
      - api
    environment:
      - API_HOST=http://api:8911

  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
