version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api_serve
    ports:
      - 8911:8911
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_S3_ENDPOINT=${MINIO_S3_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_S3_REGION=${MINIO_S3_REGION}
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: web_serve
      args:
        - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
        - MINIO_S3_ENDPOINT=${MINIO_S3_ENDPOINT}
    ports:
      - 8910:8910
    depends_on:
      - api
    environment:
      - API_HOST=http://api:8911
  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  # After starting with `docker compose -f ./docker-compose.prod.yml up`,
  # use the console to run commands in the container:
  #
  # ```
  # docker compose -f ./docker-compose.prod.yml run --rm -it console /bin/bash
  # ```
  console:
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
      target: console
    tmpfs:
      - /tmp
    command: "true"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
volumes:
  db-data: {}
networks: {}
