---
- name: Assert caddyfile_name is defined
  tags:
    - install_caddy
    - update_caddy_config
  ansible.builtin.assert:
    that:
      - caddyfile_name is defined
      - caddyfile_name is string
      - caddyfile_name | length > 0

- name: Assert alert_email_ssl_certificate is defined
  tags:
    - install_caddy
    - update_caddy_config
  ansible.builtin.assert:
    that:
      - alert_email_ssl_certificate is defined
      - alert_email_ssl_certificate is string
      - alert_email_ssl_certificate | length > 0

- name: Add Caddy GPG key
  tags:
    - install_caddy
    - add_caddy_gpg_key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /etc/apt/keyrings/caddy-stable.asc
    mode: "0644"
    force: true

- name: Add Caddy repository
  tags:
    - install_caddy
    - add_caddy_repository
  block:
    - name: Add repository
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/etc/apt/keyrings/caddy-stable.asc]
          https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present
        update_cache: true

- name: Install Caddy
  tags:
    - install_caddy
  ansible.builtin.apt:
    update_cache: true
    name: caddy
    state: present

- name: Create /etc/caddy/Caddyfile
  tags:
    - install_caddy
    - update_caddy_config
  ansible.builtin.template:
    src: "{{ caddyfile_name }}"
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload caddy
