const GalleryTags = [
  { Tag: 'AKT UND EROTIK', Weight: '1' },
  { Tag: 'FOTOTHERAPIE', Weight: '1' },
  { Tag: 'NATURPROJEKT', Weight: '1' },
  { Tag: 'SHIBARI', Weight: '1' },
  { Tag: 'PORTRAIT', Weight: '2' },
  { Tag: 'STUDIO', Weight: '2' },
  { Tag: 'PROJEKTE', Weight: '2' },
  { Tag: 'FRAUENBILDER', Weight: '2' },
  { Tag: 'MANNERPORTRAIT', Weight: '2' },
  { Tag: 'NATUR UND TIER', Weight: '3' },
  { Tag: 'OLDTIMER UND BIKES', Weight: '3' },
  { Tag: 'FAMILIEN UND PAARE', Weight: '3' },
  { Tag: 'STEAMPUNK', Weight: '3' },
  { Tag: 'KINKY', Weight: '4' },
  { Tag: 'MUSIK UND TANZ', Weight: '4' },
  { Tag: 'PRODUKTE UND INSEZNIERUNGEN', Weight: '4' },
  { Tag: 'TATTOO', Weight: '4' },
  { Tag: 'BOUDOIR UND GLAMOUR', Weight: '5' },
  { Tag: 'ANLASSE', Weight: '5' },
  { Tag: 'BEWERBUNG', Weight: '5' },
  { Tag: 'KIDS', Weight: '5' },
  { Tag: 'FANTASIE UND COSPLAY', Weight: '6' },
  { Tag: 'BABYBAUCH UND NEWBORN', Weight: '6' },
  { Tag: 'ESSEN UND GETRANKE', Weight: '6' },
  { Tag: 'DROHNE', Weight: '6' },
]

export default GalleryTags
