@proxy-staging-update: check-BW_SESSION-is-set
    @ansible-playbook -i inventory/inventory.yml playbook-proxy-management.yml -t update_caddy_config -l t4s-ctb-vps-eros

@check-BW_SESSION-is-set:
    if [ -z "${BW_SESSION}" ]; then \
        echo "BW_SESSION is not set"; \
        exit 1; \
    fi
